FROM python:3.11-slim

WORKDIR /app

COPY web_requirements.txt /app/web_requirements.txt
RUN pip install --no-cache-dir -r /app/web_requirements.txt

COPY . /app

EXPOSE 8000

CMD ["uvicorn", "web_app.main:app", "--host", "0.0.0.0", "--port", "8000"]
